"""initial migration

Revision ID: 0b3ceed6b9f3
Revises: 
Create Date: 2025-11-27 10:44:27.771575

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0b3ceed6b9f3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ##
    op.add_column('categories', sa.Column('image_public_id', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###
    


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('categories', 'image_public_id')
    # ### end Alembic commands ###