"""some changes

Revision ID: 162e5db2569a
Revises: 4af86049bdf7
Create Date: 2025-11-27 11:04:27.666440

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '162e5db2569a'
down_revision = '4af86049bdf7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
