"""describe your changes

Revision ID: 3fe71e54b8e1
Revises: 162e5db2569a
Create Date: 2025-11-27 11:06:31.277299

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3fe71e54b8e1'
down_revision = '162e5db2569a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
