"""initial

Revision ID: b28b532835af
Revises: 188db8670fa4
Create Date: 2025-11-28 20:13:48.001508

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b28b532835af'
down_revision = '188db8670fa4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_inventory_product_id', table_name='inventory')
    op.create_index('idx_inventory_variant', 'inventory', ['variant_id'], unique=False)
    op.create_foreign_key(None, 'inventory', 'product_variants', ['variant_id'], ['id'], ondelete='CASCADE')
    op.drop_column('inventory', 'product_id')
    op.add_column('product_variants', sa.Column('color', sa.String(length=50), nullable=True))
    op.add_column('product_variants', sa.Column('size', sa.String(length=50), nullable=True))
    op.add_column('product_variants', sa.Column('weight', sa.String(length=20), nullable=True))
    op.add_column('product_variants', sa.Column('additional_price', sa.DECIMAL(precision=10, scale=2), nullable=True))
    op.alter_column('product_variants', 'variant_name',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.drop_column('product_variants', 'price')
    op.drop_column('product_variants', 'image_url')
    op.drop_column('product_variants', 'attributes')
    op.drop_column('product_variants', 'stock_quantity')
    op.drop_column('product_variants', 'image_public_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_variants', sa.Column('image_public_id', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('product_variants', sa.Column('stock_quantity', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('product_variants', sa.Column('attributes', mysql.JSON(), nullable=True))
    op.add_column('product_variants', sa.Column('image_url', mysql.VARCHAR(length=500), nullable=True))
    op.add_column('product_variants', sa.Column('price', mysql.DECIMAL(precision=10, scale=2), nullable=True))
    op.alter_column('product_variants', 'variant_name',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.drop_column('product_variants', 'additional_price')
    op.drop_column('product_variants', 'weight')
    op.drop_column('product_variants', 'size')
    op.drop_column('product_variants', 'color')
    op.add_column('inventory', sa.Column('product_id', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'inventory', type_='foreignkey')
    op.drop_index('idx_inventory_variant', table_name='inventory')
    op.create_index('ix_inventory_product_id', 'inventory', ['product_id'], unique=False)
    # ### end Alembic commands ###
