"""add_clothing_fields

Revision ID: b810e5c399fe
Revises: b28b532835af
Create Date: 2025-11-29 13:40:05.133568

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b810e5c399fe'
down_revision = 'b28b532835af'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_table('brands', ...) - Table already exists
    op.add_column('categories', sa.Column('size_guide_image_url', sa.String(length=500), nullable=True))
    op.add_column('product_images', sa.Column('variant_id', sa.Integer(), nullable=True))
    op.create_index('idx_product_image_variant', 'product_images', ['variant_id'], unique=False)
    op.create_index(op.f('ix_product_images_variant_id'), 'product_images', ['variant_id'], unique=False)
    op.create_foreign_key(None, 'product_images', 'product_variants', ['variant_id'], ['id'], ondelete='SET NULL')
    op.add_column('products', sa.Column('material', sa.String(length=255), nullable=True))
    op.add_column('products', sa.Column('care_instructions', sa.Text(), nullable=True))
    op.add_column('products', sa.Column('brand_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_products_brand_id'), 'products', ['brand_id'], unique=False)
    op.create_foreign_key(None, 'products', 'brands', ['brand_id'], ['id'], ondelete='SET NULL')
    op.drop_column('products', 'brand')
    op.add_column('reviews', sa.Column('fit_rating', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reviews', 'fit_rating')
    op.add_column('products', sa.Column('brand', mysql.VARCHAR(length=100), nullable=True))
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_index(op.f('ix_products_brand_id'), table_name='products')
    op.drop_column('products', 'brand_id')
    op.drop_column('products', 'care_instructions')
    op.drop_column('products', 'material')
    op.drop_constraint(None, 'product_images', type_='foreignkey')
    op.drop_index(op.f('ix_product_images_variant_id'), table_name='product_images')
    op.drop_index('idx_product_image_variant', table_name='product_images')
    op.drop_column('product_images', 'variant_id')
    op.drop_column('categories', 'size_guide_image_url')
    op.create_table('token_blacklist',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('jti', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('revoked', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('expires_at', mysql.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('jti', 'token_blacklist', ['jti'], unique=False)
    op.create_index('ix_token_blacklist_id', 'token_blacklist', ['id'], unique=False)
    op.create_table('email_verification_tokens',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('token', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('expires_at', mysql.DATETIME(), nullable=False),
    sa.Column('used', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='email_verification_tokens_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_email_verification_tokens_user_id', 'email_verification_tokens', ['user_id'], unique=False)
    op.create_index('ix_email_verification_tokens_token', 'email_verification_tokens', ['token'], unique=False)
    op.create_index('ix_email_verification_tokens_id', 'email_verification_tokens', ['id'], unique=False)
    op.create_table('password_reset_tokens',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('token', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('verification_code', mysql.VARCHAR(length=6), nullable=False),
    sa.Column('code_verified', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('expires_at', mysql.DATETIME(), nullable=False),
    sa.Column('used', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='password_reset_tokens_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_password_reset_tokens_verification_code', 'password_reset_tokens', ['verification_code'], unique=False)
    op.create_index('ix_password_reset_tokens_user_id', 'password_reset_tokens', ['user_id'], unique=False)
    op.create_index('ix_password_reset_tokens_token', 'password_reset_tokens', ['token'], unique=False)
    op.create_index('ix_password_reset_tokens_id', 'password_reset_tokens', ['id'], unique=False)
    # op.drop_table('brands') - Table should persist
    # ### end Alembic commands ###
