"""models.py creation

Revision ID: cec09dd569c5
Revises: 1c0ab6876c2c
Create Date: 2025-12-21 17:21:11.978063

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cec09dd569c5'
down_revision = '1c0ab6876c2c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coupon_reward_rules', sa.Column('threshold_amount', sa.DECIMAL(precision=10, scale=2), nullable=True, comment='Minimum order amount to trigger (for ORDER_AMOUNT type)'))
    op.add_column('coupon_reward_rules', sa.Column('threshold_count', sa.Integer(), nullable=True, comment='Number of orders to trigger (for ORDER_COUNT type)'))
    op.add_column('coupon_reward_rules', sa.Column('coupon_discount_type', sa.String(length=20), nullable=False, comment="'percentage' or 'fixed_amount'"))
    op.add_column('coupon_reward_rules', sa.Column('coupon_discount_value', sa.DECIMAL(precision=10, scale=2), nullable=False, comment='Discount value (percentage or fixed amount)'))
    op.add_column('coupon_reward_rules', sa.Column('coupon_minimum_order', sa.DECIMAL(precision=10, scale=2), nullable=True, comment='Minimum order amount to use the coupon'))
    op.add_column('coupon_reward_rules', sa.Column('coupon_maximum_discount', sa.DECIMAL(precision=10, scale=2), nullable=True, comment='Maximum discount amount (for percentage discounts)'))
    op.add_column('coupon_reward_rules', sa.Column('coupon_valid_days', sa.Integer(), nullable=False, comment='Number of days the coupon is valid after generation'))
    op.add_column('coupon_reward_rules', sa.Column('is_one_time', sa.Boolean(), nullable=False, comment='If true, customer can only receive this coupon once'))
    op.add_column('coupon_reward_rules', sa.Column('priority', sa.Integer(), nullable=False, comment='Higher priority rules are evaluated first'))
    op.alter_column('coupon_reward_rules', 'trigger_type',
               existing_type=mysql.VARCHAR(length=20),
               comment=None,
               existing_comment='order_amount or product_count',
               existing_nullable=False)
    op.create_index('idx_coupon_rule_active', 'coupon_reward_rules', ['is_active'], unique=False)
    op.create_index('idx_coupon_rule_trigger', 'coupon_reward_rules', ['trigger_type'], unique=False)
    op.drop_column('coupon_reward_rules', 'reward_max_discount')
    op.drop_column('coupon_reward_rules', 'threshold_value')
    op.drop_column('coupon_reward_rules', 'reward_discount_type')
    op.drop_column('coupon_reward_rules', 'reward_discount_value')
    op.drop_column('coupon_reward_rules', 'reward_minimum_order')
    op.drop_column('coupon_reward_rules', 'reward_valid_days')
    op.drop_column('coupon_reward_rules', 'one_time_per_user')
    op.alter_column('inventory', 'reserved_quantity',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.add_column('user_coupons', sa.Column('triggered_by_order_id', sa.Integer(), nullable=True))
    op.add_column('user_coupons', sa.Column('used_on_order_id', sa.Integer(), nullable=True))
    op.add_column('user_coupons', sa.Column('is_public', sa.Boolean(), nullable=False, comment='If true, this coupon can be used by any user (promo code)'))
    op.add_column('user_coupons', sa.Column('name', sa.String(length=100), nullable=True, comment="Display name for the coupon (e.g., 'Summer Sale')"))
    op.add_column('user_coupons', sa.Column('description', sa.String(length=500), nullable=True, comment='Description of the coupon'))
    op.add_column('user_coupons', sa.Column('usage_limit', sa.Integer(), nullable=True, comment='For public coupons: max number of times it can be used'))
    op.add_column('user_coupons', sa.Column('usage_count', sa.Integer(), nullable=False, comment='For public coupons: how many times it has been used'))
    op.alter_column('user_coupons', 'user_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('user_coupons', 'discount_type',
               existing_type=mysql.VARCHAR(length=20),
               comment=None,
               existing_comment='percentage or fixed_amount',
               existing_nullable=False)
    op.create_index('idx_user_coupon_code', 'user_coupons', ['code'], unique=False)
    op.create_index('idx_user_coupon_used', 'user_coupons', ['is_used'], unique=False)
    op.create_index('idx_user_coupon_user', 'user_coupons', ['user_id'], unique=False)
    op.create_index('idx_user_coupon_valid', 'user_coupons', ['valid_until'], unique=False)
    op.create_index(op.f('ix_user_coupons_triggered_by_order_id'), 'user_coupons', ['triggered_by_order_id'], unique=False)
    op.drop_constraint('user_coupons_ibfk_3', 'user_coupons', type_='foreignkey')
    op.create_foreign_key(None, 'user_coupons', 'orders', ['triggered_by_order_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'user_coupons', 'orders', ['used_on_order_id'], ['id'], ondelete='SET NULL')
    op.drop_column('user_coupons', 'used_order_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_coupons', sa.Column('used_order_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'user_coupons', type_='foreignkey')
    op.drop_constraint(None, 'user_coupons', type_='foreignkey')
    op.create_foreign_key('user_coupons_ibfk_3', 'user_coupons', 'orders', ['used_order_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_user_coupons_triggered_by_order_id'), table_name='user_coupons')
    op.drop_index('idx_user_coupon_valid', table_name='user_coupons')
    op.drop_index('idx_user_coupon_user', table_name='user_coupons')
    op.drop_index('idx_user_coupon_used', table_name='user_coupons')
    op.drop_index('idx_user_coupon_code', table_name='user_coupons')
    op.alter_column('user_coupons', 'discount_type',
               existing_type=mysql.VARCHAR(length=20),
               comment='percentage or fixed_amount',
               existing_nullable=False)
    op.alter_column('user_coupons', 'user_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.drop_column('user_coupons', 'usage_count')
    op.drop_column('user_coupons', 'usage_limit')
    op.drop_column('user_coupons', 'description')
    op.drop_column('user_coupons', 'name')
    op.drop_column('user_coupons', 'is_public')
    op.drop_column('user_coupons', 'used_on_order_id')
    op.drop_column('user_coupons', 'triggered_by_order_id')
    op.alter_column('inventory', 'reserved_quantity',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.add_column('coupon_reward_rules', sa.Column('one_time_per_user', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False, comment='If true, user can only receive this reward once'))
    op.add_column('coupon_reward_rules', sa.Column('reward_valid_days', mysql.INTEGER(), autoincrement=False, nullable=False, comment='How many days the coupon is valid'))
    op.add_column('coupon_reward_rules', sa.Column('reward_minimum_order', mysql.DECIMAL(precision=10, scale=2), nullable=True, comment='Minimum order amount to use the coupon'))
    op.add_column('coupon_reward_rules', sa.Column('reward_discount_value', mysql.DECIMAL(precision=10, scale=2), nullable=False, comment='Discount value (% or $)'))
    op.add_column('coupon_reward_rules', sa.Column('reward_discount_type', mysql.VARCHAR(length=20), nullable=False, comment='percentage or fixed_amount'))
    op.add_column('coupon_reward_rules', sa.Column('threshold_value', mysql.DECIMAL(precision=10, scale=2), nullable=False, comment='Amount in dollars or number of products'))
    op.add_column('coupon_reward_rules', sa.Column('reward_max_discount', mysql.DECIMAL(precision=10, scale=2), nullable=True, comment='Maximum discount amount for percentage discounts'))
    op.drop_index('idx_coupon_rule_trigger', table_name='coupon_reward_rules')
    op.drop_index('idx_coupon_rule_active', table_name='coupon_reward_rules')
    op.alter_column('coupon_reward_rules', 'trigger_type',
               existing_type=mysql.VARCHAR(length=20),
               comment='order_amount or product_count',
               existing_nullable=False)
    op.drop_column('coupon_reward_rules', 'priority')
    op.drop_column('coupon_reward_rules', 'is_one_time')
    op.drop_column('coupon_reward_rules', 'coupon_valid_days')
    op.drop_column('coupon_reward_rules', 'coupon_maximum_discount')
    op.drop_column('coupon_reward_rules', 'coupon_minimum_order')
    op.drop_column('coupon_reward_rules', 'coupon_discount_value')
    op.drop_column('coupon_reward_rules', 'coupon_discount_type')
    op.drop_column('coupon_reward_rules', 'threshold_count')
    op.drop_column('coupon_reward_rules', 'threshold_amount')
    op.create_table('email_verification_tokens',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('token', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('expires_at', mysql.DATETIME(), nullable=False),
    sa.Column('used', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='email_verification_tokens_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_email_verification_tokens_user_id', 'email_verification_tokens', ['user_id'], unique=False)
    op.create_table('token_blacklist',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('jti', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('revoked', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('expires_at', mysql.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('jti', 'token_blacklist', ['jti'], unique=False)
    op.create_index('ix_token_blacklist_id', 'token_blacklist', ['id'], unique=False)
    op.create_table('password_reset_tokens',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('token', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('verification_code', mysql.VARCHAR(length=6), nullable=False),
    sa.Column('code_verified', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('expires_at', mysql.DATETIME(), nullable=False),
    sa.Column('used', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='password_reset_tokens_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_password_reset_tokens_verification_code', 'password_reset_tokens', ['verification_code'], unique=False)
    op.create_index('ix_password_reset_tokens_user_id', 'password_reset_tokens', ['user_id'], unique=False)
    # ### end Alembic commands ###
