"""delete_clothing_fields

Revision ID: e69412ba6a27
Revises: b810e5c399fe
Create Date: 2025-11-29 15:02:22.344988

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e69412ba6a27'
down_revision = 'b810e5c399fe'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Comment out these table drops - they're not related to our changes
    # op.drop_index('ix_email_verification_tokens_id', table_name='email_verification_tokens')
    # op.drop_index('ix_email_verification_tokens_token', table_name='email_verification_tokens')
    # op.drop_index('ix_email_verification_tokens_user_id', table_name='email_verification_tokens')
    # op.drop_table('email_verification_tokens')
    # op.drop_index('ix_token_blacklist_id', table_name='token_blacklist')
    # op.drop_index('jti', table_name='token_blacklist')
    # op.drop_table('token_blacklist')
    # op.drop_index('ix_password_reset_tokens_user_id', table_name='password_reset_tokens')
    # op.drop_index('ix_password_reset_tokens_verification_code', table_name='password_reset_tokens')
    # op.drop_table('password_reset_tokens')
    
    # # Drop foreign key FIRST (before indexes)
    # try:
    #     op.drop_constraint('product_images_ibfk_2', 'product_images', type_='foreignkey')
    # except:
    #     pass  # Constraint might not exist
    
    # These indexes don't exist in the database, commenting out
    # op.drop_index('idx_product_image_variant', table_name='product_images')
    # op.drop_index('ix_product_images_variant_id', table_name='product_images')
    
    # Try to drop column if it exists
    try:
        op.drop_column('product_images', 'variant_id')
    except:
        pass  # Column might not exist
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_images', sa.Column('variant_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('product_images_ibfk_2', 'product_images', 'product_variants', ['variant_id'], ['id'], ondelete='SET NULL')
    op.create_index('ix_product_images_variant_id', 'product_images', ['variant_id'], unique=False)
    op.create_index('idx_product_image_variant', 'product_images', ['variant_id'], unique=False)
    op.create_table('password_reset_tokens',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('token', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('verification_code', mysql.VARCHAR(length=6), nullable=False),
    sa.Column('code_verified', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('expires_at', mysql.DATETIME(), nullable=False),
    sa.Column('used', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='password_reset_tokens_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_password_reset_tokens_verification_code', 'password_reset_tokens', ['verification_code'], unique=False)
    op.create_index('ix_password_reset_tokens_user_id', 'password_reset_tokens', ['user_id'], unique=False)
    op.create_table('token_blacklist',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('jti', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('revoked', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('expires_at', mysql.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('jti', 'token_blacklist', ['jti'], unique=False)
    op.create_index('ix_token_blacklist_id', 'token_blacklist', ['id'], unique=False)
    op.create_table('email_verification_tokens',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('token', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('expires_at', mysql.DATETIME(), nullable=False),
    sa.Column('used', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='email_verification_tokens_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_email_verification_tokens_user_id', 'email_verification_tokens', ['user_id'], unique=False)
    op.create_index('ix_email_verification_tokens_token', 'email_verification_tokens', ['token'], unique=False)
    op.create_index('ix_email_verification_tokens_id', 'email_verification_tokens', ['id'], unique=False)
    # ### end Alembic commands ###
